feat(xxdmem): allow to use `xxdmem -r -p`

diff --git a/xxdmem b/xxdmem
--- a/xxdmem
+++ b/xxdmem
@@ -4,6 +4,8 @@ self="$(realpath -- "$0" || printf %s "$0")"
 : "${file:=/dev/mem}"
 
 found_file=0 # 0, 1, i(gnore)
+revert=
+plain=
 for arg; do
   shift
   case "$found_file,$arg" in
@@ -12,6 +14,12 @@ for arg; do
     ;;
   0,-[cglnosR])
     found_file=i
+    ;;
+  ?,-r|?,-revert)
+    revert=1
+    ;;
+  ?,-p|?,-ps|?,-postscript|?,-plain)
+    plain=1
     ;;
   0,-*) ;;
   0,*)
@@ -24,6 +32,11 @@ for arg; do
   set -- "$@" "$arg"
 done
 
+if [ "$revert" ] && ! [ "$plain" ]; then
+  printf '%s: %s\n' "$0" "error: can only use -r together with -p" >&2
+  exit 2
+fi
+
 seek=0
 found_seek=0
 for arg; do
@@ -32,18 +45,31 @@ for arg; do
   0,-s)
     arg="-o"
     found_seek=1
+    if [ "$revert" ]; then
+      continue
+    fi
     ;;
   0,-s*)
     seek="${arg#-s}"
     arg="-o$seek"
+    if [ "$revert" ]; then
+      continue
+    fi
     ;;
   1,*)
     seek="$arg"
     found_seek=0
+    if [ "$revert" ]; then
+      continue
+    fi
     ;;
   *) ;;
   esac
   set -- "$@" "$arg"
 done
 
-"$(dirname -- "$self")"/memdump "$seek" "$file" | xxd -o "$seek" "$@"
+if [ "$revert" ]; then
+  xxd "$@" | "$(dirname -- "$self")"/memdump -r "$seek" "$file"
+else
+  "$(dirname -- "$self")"/memdump "$seek" "$file" | xxd -o "$seek" "$@"
+fi
